Began implementing routes
ctc-uci/the-literacy-project-backend pull request #21
Opened 2022-02-22 23:49 UTC by joshualchan

Finished a hand-full of routes from the [backend routes](https://docs.google.com/document/d/1WXy8aFllKR02ShNIxI5LtN8FbX7jB5yTtgn7OjQvyL8/edit?usp=sharing) doc.

2022-02-22 23:49 UTC, ctc-devops commented on routes/areas.js
> +    console.log(areaInfo);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-22 23:49 UTC, ctc-devops commented on routes/areas.js
> +    console.log(areaId);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-22 23:49 UTC, ctc-devops commented on routes/sites.js
> +    console.log(req.body);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-22 23:49 UTC, ctc-devops commented on routes/teachers.js
> +    console.log(teacherInfo);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-26 03:23 UTC, ctc-devops commented on routes/teachers.js
> +    console.error(err.message);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-26 03:23 UTC, ctc-devops commented on routes/teachers.js
> +    console.error(err.message);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-26 03:23 UTC, ctc-devops commented on routes/teachers.js
> +  console.log(req.body);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-26 03:23 UTC, ctc-devops commented on routes/teachers.js
> +    console.error(err.message);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-03-09 01:01 UTC, anikait-rao requested changes
A few minor changes. The two additional routes I requested can either be done right now or I can make a task for it for next sprint LMK

2022-03-09 01:01 UTC, anikait-rao commented on server/database.sql
>  CREATE TYPE season AS ENUM('winter', 'spring', 'summer', 'fall');
Can the season enum be changed to 1,2,3,4 instead of the actual season names. The cycles don't necessarily correspond to the seasons

2022-03-09 01:01 UTC, anikait-rao commented on routes/studentGroups.js
> +
not urgent, but a route to get all student groups for a given teacher in this file would be nice

2022-03-09 01:01 UTC, anikait-rao commented on routes/students.js
similar thing in this file, it would be helpful in the future to have a route where we can get all students for a given teacher

2022-03-09 01:01 UTC, anikait-rao commented on server/database.sql
>    group_id SERIAL PRIMARY KEY,
I can't comment that line for whatever reason, but please change the `site` table so that deleting an area does not cascade and delete all the corresponding sites

2022-03-09 01:07 UTC, anikait-rao commented on server/database.sql
>    year INT NOT NULL,
This is supposed to be a school year, not a calendar year

2022-03-09 02:31 UTC, anikait-rao commented on server/database.sql
>  DROP TABLE area CASCADE;
I think site should also have an active status (the same way area has one)

2022-03-09 06:18 UTC, anikait-rao approved these changes
Looks good, merging

2022-03-09 06:18 UTC, merged